# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 7.5921822461753337
    has_acceleration_limits: true
    max_acceleration: 75.921822461753337
    has_jerk_limits: false
  joint_2:
    has_velocity_limits: true
    max_velocity: 6.719517620178169
    has_acceleration_limits: true
    max_acceleration: 67.19517620178169
    has_jerk_limits: false
  joint_3:
    has_velocity_limits: true
    max_velocity: 8.7266462599716483
    has_acceleration_limits: true
    max_acceleration: 87.266462599716483
    has_jerk_limits: false
  joint_4:
    has_velocity_limits: true
    max_velocity: 17.366026057343579
    has_acceleration_limits: true
    max_acceleration: 173.66026057343579
    has_jerk_limits: false
  joint_5:
    has_velocity_limits: true
    max_velocity: 18.587756533739611
    has_acceleration_limits: true
    max_acceleration: 185.87756533739611
    has_jerk_limits: false
  joint_6:
    has_velocity_limits: true
    max_velocity: 25.220007691318063
    has_acceleration_limits: true
    max_acceleration: 252.20007691318063
    has_jerk_limits: false
