controller_names:
  - manipulator_controller

manipulator_controller:
  action_ns: joint_trajectory_action
  type: FollowJointTrajectory
  default: true
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6